/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 can.gltf
*/
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/can.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cylinder_2.geometry} material={materials.Wrapper} />
    </group>
  )
}

useGLTF.preload('/can.gltf')
